/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppToolBar: typeof import('./components/AppToolBar.vue')['default']
    ExternalRedirect: typeof import('./components/ExternalRedirect.vue')['default']
    MapotofuIcon: typeof import('./components/MapotofuIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
